version: '3.9'
services:
  user-service-db:
    image: prismagraphql/mongo-single-replica:4.2.17-bionic

    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      INIT_WAIT_SEC: 5
    volumes:
      - user-service-volume:/data/db

volumes:
  user-service-volume:

# this image does not work currently, an issue can be opened or we can have a create a separate image
# that will create a replica set. For now I will be using mongodb cloud as it offers replica set config
# out of the box.